version: 2.1

orbs:
  sample-orb: enokawa/sample-orb@0.0.1

jobs:
  build:
    docker:
    - image: bash
    steps:
    - run: print username
    - sample-orb/hello:
        username: "enokawa"

workflows:
  main:
    jobs:
    - build

